% special video

%%
% Bezier curves used, I made a small collection so far

% semicircle
CtrlPtsArray = {[...
  [-1,0]',...
  [-1,(4/3)*tan(pi/8)]',...
  [-(4/3)*tan(pi/8),1]',...
  [0,1]'...
  ],[...
  [0,1]',...
  [0,0.5]',...
  [0,-0.5]',...
  [0,-1]'...
  ],[...
  [0,-1]',...
  [-(4/3)*tan(pi/8),-1]',...
  [-1,-(4/3)*tan(pi/8)]',...
  [-1,0]'...
  ]};

%%
% parameters

% technical stuff
MaxDistDelta = 0.001;
CloseTol = 0.001;
MaxSpins = 100;

% designer stuff
MarkerAngle0 = pi;

%% do curves
[WheelRadius, MarkerRadius, BezierPos, ...
  WhCtrPos1, MarkerPos1, MarkerAngle1,...
  WhCtrPos2, MarkerPos2, MarkerAngle2] = ...
  SetupCurves_2pts( CtrlPtsArray, 47/7, 2/3, MarkerAngle0, ...
    MaxDistDelta, CloseTol, MaxSpins);

% preview
figure()
fill(BezierPos(1,:),BezierPos(2,:), 'k', 'EdgeColor', 'none'); 
hold on
axis equal
grid on
plot(MarkerPos1(1,:),MarkerPos1(2,:),'yellow')
plot(MarkerPos2(1,:),MarkerPos2(2,:),'magenta')