% the code for the curve is known to work, this should be the first real
% example
% the sketch of the moon took me some time, as I did it analytically

% designer stuff
MarkerAngle0 = pi;

% specific to this example
WheelRadius  = 1;
MarkerRadius = WheelRadius;

% technical stuff
MaxDistDelta = 0.1;
MarkerSpeed  = 1;

% specially crafted control points
CtrlPtsArray = {[...
  [-1,0]', ...
  [-1,0]'+(4/3)*(tan(pi/8)/sin(pi/2))*[0,1]',...
  [0,1]'-(4/3)*(tan(pi/8)/sin(pi/2))*[sin(pi/2),cos(pi/2)]',...
  [0,1]'...
  ],[...
  [0,1]', ...
  [0,1]' -(4/3)*(tan(pi/6)/sin(pi/3))*[sin(pi/3), cos(pi/3)]',...
  [0,-1]'-(4/3)*(tan(pi/6)/sin(pi/3))*[sin(pi/3),-cos(pi/3)]',...
  [0,-1]'...
  ],[...
  [0,-1]', ...
  [0,-1]'-(4/3)*(tan(pi/8)/sin(pi/2))*[sin(pi/2),-cos(pi/2)]',...
  [-1,0]'-(4/3)*(tan(pi/8)/sin(pi/2))*[0,1]',...
  [-1,0]' ...
  ]};

% spirograph curve
[Time, WhCtrPos, MarkerPos, MarkerAngle] = ...
  AllBeziers( CtrlPtsArray, WheelRadius, MarkerRadius, MarkerAngle0, ...
    MaxDistDelta, MarkerSpeed, ...
    CloseTol, MaxSpins);



% plot everything
figure()
plot(BezierPos(1,:),BezierPos(2,:),'blue')
hold on
plot(WhCtrPos(1,:),WhCtrPos(2,:),'green')
axis equal
grid on
plot(MarkerPos(1,:),MarkerPos(2,:),'yellow')