% Corner case: the wheel can't continue rolling on the current curve
% because it will collide with the next curve.
% Search all corners from the shape generated by the Bezier curves, then
% removes them.
%
% ---- INUPUT ------------------------------------------------------------
%       Curve1/2  Array with control points for each one of the Bezier
%                 curves that make the curve {?} <- [2,4]'s
%            Tol  Max distance between points of the discretization [1]
%
% ---- OUTPUT ------------------------------------------------------------
% Curve1/2_short  Array with control points for each one of the Bezier
%                 curves AFTER replacing the corner portion {?} <- [2,4]'s
%           Time  Timestamps [1x?]
%       WhCtrPos  Location of the wheel center at timestamps [2x?]
%      MarkerPos  Location of marker at timepoints [2x?]
%
% The last control point of the last curve must be equal to the first
% control point of the first curve. This is not checked.
%
function Rescale( obj, ScaleFactor, varargin )

% by default, the center of scaling is the origin
if size(varargin)>0
  Center = varargin{1}; 
else
  Center = [0,0]';
end

% actual rescaling is simple
obj.CtrlPts = ( obj.CtrlPts - Center )*ScaleFactor + Center;

end