% Corner case: the wheel can't continue rolling on the current curve
% because it will collide with the next curve.
% Search all corners from the shape generated by the Bezier curves, then
% removes them.
%
% ---- INUPUT ------------------------------------------------------------
%       Curve1/2  Array with control points for each one of the Bezier
%                 curves that make the curve {?} <- [2,4]'s
%            Tol  Max distance between points of the discretization [1]
%
% ---- OUTPUT ------------------------------------------------------------
% Curve1/2_short  Array with control points for each one of the Bezier
%                 curves AFTER replacing the corner portion {?} <- [2,4]'s
%           Time  Timestamps [1x?]
%       WhCtrPos  Location of the wheel center at timestamps [2x?]
%      MarkerPos  Location of marker at timepoints [2x?]
%
% The last control point of the last curve must be equal to the first
% control point of the first curve. This is not checked.
%
function FitBox( obj, MaxRange, varargin )

% by default, the center is the origin
if ~isempty(varargin)
  Center = varargin{1};
else
  Center = [0,0]';
end

MaxRangeX = MaxRange(1);
MaxRangeY = MaxRange(2);

% init
minX = Inf;
maxX = -Inf;
minY = Inf;
maxY = -Inf;

% rudimentary bounding box, designed to be fast
% doesn't account for the actual curve, only control points
for i = 1:obj.nSegments
  currSegment = obj.Segment{i};
  currCtrlPts = currSegment.CtrlPts;
  % ony first and last control points are part of the curve
  minX = min( [minX, currCtrlPts(1,1), currCtrlPts(1,4)] );
  maxX = max( [maxX, currCtrlPts(1,1), currCtrlPts(1,4)] );
  minY = min( [minY, currCtrlPts(2,1), currCtrlPts(2,4)] );
  maxY = max( [maxY, currCtrlPts(2,1), currCtrlPts(2,4)] );
end
RangeX = maxX - minX;
RangeY = maxY - minY;

% the scale factor should guarantee that final size fits the limits
if RangeY * (MaxRangeX / RangeX) <= MaxRangeY
  scaleFactor = (MaxRangeX / RangeX);
elseif RangeX * (MaxRangeY / RangeY) <= MaxRangeX
  scaleFactor = (MaxRangeY / RangeY);
end

% scaling per se
for i = 1:obj.nSegments
  obj.Segment{i}.Rescale( scaleFactor, Center );
end

end