% Corner case: the wheel can't continue rolling on the current curve
% because it will collide with the next curve.
% Search all corners from the shape generated by the Bezier curves, then
% removes them.
%
% ---- INUPUT ------------------------------------------------------------
%       Curve1/2  Array with control points for each one of the Bezier
%                 curves that make the curve {?} <- [2,4]'s
%            Tol  Max distance between points of the discretization [1]
%
% ---- OUTPUT ------------------------------------------------------------
% Curve1/2_short  Array with control points for each one of the Bezier
%                 curves AFTER replacing the corner portion {?} <- [2,4]'s
%           Time  Timestamps [1x?]
%       WhCtrPos  Location of the wheel center at timestamps [2x?]
%      MarkerPos  Location of marker at timepoints [2x?]
%
% The last control point of the last curve must be equal to the first
% control point of the first curve. This is not checked.
%
function obj_return = RemoveAllCorners( obj, WheelRadius )

CornerAngles = zeros(1,obj.nSegments);
nSegments_new = obj.nSegments;

% an array that will be changed multiple times
Segment_copy = obj.Segment;
Segment_roll = cell( 1, obj.nSegments );

% check for corners
for i = 1:obj.nSegments
  % next curve may be the first curve
  i_ = mod( i+1-1, obj.nSegments ) +1;
  %
  % find the cornering angle
  SegmentPrev = Segment_copy{i};
  SegmentPost = Segment_copy{i_};
  TangentPre = SegmentPrev.EvalNormal( 1, WheelRadius );
  TangentPos = SegmentPost.EvalNormal( 0, WheelRadius );
  if (norm(TangentPos)>obj.Tol) && (norm(TangentPre)>obj.Tol)
    CornerAngles(i) = mod( atan2(TangentPre(2),TangentPre(1)) - atan2(TangentPos(2),TangentPos(1)), 2*pi);
  else
    % exception: vanishing first derivative; throw to exception handler
    CornerAngles(i) = pi;
  end
  %
  % only act if wheel can't roll freely
  % worst-case scenario found: if the corner angle is -pi
  if CornerAngles(i) >= pi
    if (CornerAngles(i) == pi)&&(obj.SkipNegPi)
      CornerAngles(i) = 0;
      continue
    end
    CtrlPtsPrev = SegmentPrev.CtrlPts;
    CtrlPtsPost = SegmentPost.CtrlPts;
    [SuccessFlag, CtrlPtsPrev_new, CtrlPtsPost_new, CtrlPts_roll] = ...
      SegmentPrev.RemoveSingleCorner( CtrlPtsPrev, CtrlPtsPost, WheelRadius );
    %
    if SuccessFlag
      Segment_copy{i}  = CtrlPtsPrev_new;
      Segment_copy{i_} = CtrlPtsPost_new;
      Segment_roll{i}  = CtrlPts_roll;
      nSegments_new    = nSegments_new + 1;
    end
  end
end

% get auxiliary curves in line
Segment_new = cell( 1, nSegments_new );
idx_cell = 1;
for i = 1:obj.nSegments
  Segment_new{idx_cell} = Segment_copy{i};
  idx_cell = idx_cell + 1;
  if CornerAngles(i) >= pi
    Segment_new{idx_cell} = Segment_roll{i};
    idx_cell = idx_cell + 1;
  end
end

% remove curves with all 4 points equal to each other
obj_return = Segment( Segment_new );
obj_return = obj_return.RemovePointCurves( Segment_new );

end