% Corner case: the wheel can't continue rolling on the current curve
% because it will collide with the next curve.
% Search all corners from the shape generated by the Bezier curves, then
% removes them.
%
% ---- INUPUT ------------------------------------------------------------
%       Curve1/2  Array with control points for each one of the Bezier
%                 curves that make the curve {?} <- [2,4]'s
%            Tol  Max distance between points of the discretization [1]
%
% ---- OUTPUT ------------------------------------------------------------
% Curve1/2_short  Array with control points for each one of the Bezier
%                 curves AFTER replacing the corner portion {?} <- [2,4]'s
%           Time  Timestamps [1x?]
%       WhCtrPos  Location of the wheel center at timestamps [2x?]
%      MarkerPos  Location of marker at timepoints [2x?]
%
% The last control point of the last curve must be equal to the first
% control point of the first curve. This is not checked.
%
function obj_return = RemoveAllCorners( obj, varargin )

% by default, use the corner rounding radius
if ~isempty(varargin)
  WheelRadius = varargin{1};
else
  WheelRadius = obj.CornerRoundingRadius;
end

CornerAngles = zeros(1,obj.nSegments);
nSegments_new = obj.nSegments;

% an array that will be changed multiple times
Segment_copy = obj.Segment;
Segment_roll = cell( 1, obj.nSegments );

% check for corners
for i = 1:obj.nSegments
  % next curve may be the first curve
  i_ = mod( i+1-1, obj.nSegments ) +1;
  %
  % find the cornering angle
  SegmentPrev = Segment_copy{i};
  SegmentPost = Segment_copy{i_};
  NormalPre = SegmentPrev.EvalNormal( 1 );
  NormalPos = SegmentPost.EvalNormal( 0 );
  if (norm(NormalPos)>obj.Tol) && (norm(NormalPre)>obj.Tol)
    CornerAngles(i) = mod( atan2(NormalPre(2),NormalPre(1)) - atan2(NormalPos(2),NormalPos(1)), 2*pi);
  else
    % exception: vanishing first derivative; throw to exception handler
    CornerAngles(i) = pi;
  end
  %
  % only act if wheel can't roll freely
  % worst-case scenario found: if the corner angle is -pi
  if CornerAngles(i) >= pi
    if (CornerAngles(i) == pi)&&(obj.SkipNegPi)
      CornerAngles(i) = 0;
      continue
    end
    CtrlPtsPrev = SegmentPrev.CtrlPts;
    CtrlPtsPost = SegmentPost.CtrlPts;
    [SuccessFlag, CtrlPtsPrev_new, CtrlPtsPost_new, CtrlPts_roll] = ...
      BezPath.RemoveSingleCorner( CtrlPtsPrev, CtrlPtsPost, WheelRadius );
    %
    if SuccessFlag
      Segment_copy{i}  = BezSegment( CtrlPtsPrev_new );
      Segment_copy{i_} = BezSegment( CtrlPtsPost_new );
      Segment_roll{i}  = BezSegment( CtrlPts_roll );
      nSegments_new    = nSegments_new + 1;
    end
  end
end

% get auxiliary curves in line
CtrlPtsArray = cell( 1, nSegments_new );
idx_cell = 1;
for i = 1:obj.nSegments
  CtrlPtsArray{idx_cell} = Segment_copy{i}.CtrlPts;
  idx_cell = idx_cell + 1;
  if CornerAngles(i) >= pi
    CtrlPtsArray{idx_cell} = Segment_roll{i}.CtrlPts;
    idx_cell = idx_cell + 1;
  end
end

% remove curves with all 4 points equal to each other
obj_return = BezPath( 'CtrlPtsArray', CtrlPtsArray );
obj_return.RemovePointCurves();

end